import os
import io
import ast
from glob import glob
import os
from setuptools import setup
from setuptools import find_packages


def _install_conda_cuda_hook():
    # CLAUDE-OPTIMIZE: make `pip install -e .` self-configuring for the GPU.
    # The pip CUDA wheels (nvidia-*-cu12) live in site-packages/nvidia/*/lib and
    # TensorFlow needs them on LD_LIBRARY_PATH *before* python starts (the linker
    # reads it once at process start). When we are being installed into a conda
    # env, drop an activation hook so even a bare `import tensorflow` finds the
    # GPU with no manual step. Outside conda there is no CONDA_PREFIX, so this is
    # a no-op and gpuSolve/__init__.py still sets the path and re-execs at import.
    conda_prefix = os.environ.get('CONDA_PREFIX')
    if not conda_prefix or not os.path.isdir(conda_prefix):
        return
    activate_dir   = os.path.join(conda_prefix, 'etc', 'conda', 'activate.d')
    deactivate_dir = os.path.join(conda_prefix, 'etc', 'conda', 'deactivate.d')
    # glob nvidia/*/lib at activation time (not install time) so the hook is
    # robust to the env's python version and to wheels added later.
    activate_sh = (
        '#!/bin/bash\n'
        '# Auto-generated by PDEnsorflow setup.py: put the pip-installed CUDA\n'
        '# (nvidia-*-cu12) libs and the env lib dir on LD_LIBRARY_PATH so that\n'
        '# TensorFlow can dlopen them without importing gpuSolve first.\n'
        'export _PDENSORFLOW_OLD_LD_LIBRARY_PATH="${LD_LIBRARY_PATH}"\n'
        '_pdt_nv=""\n'
        'for _pdt_d in "${CONDA_PREFIX}"/lib/python*/site-packages/nvidia/*/lib; do\n'
        '    [ -d "${_pdt_d}" ] && _pdt_nv="${_pdt_nv}${_pdt_d}:"\n'
        'done\n'
        'export LD_LIBRARY_PATH="${_pdt_nv}${CONDA_PREFIX}/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"\n'
        'unset _pdt_nv _pdt_d\n'
    )
    deactivate_sh = (
        '#!/bin/bash\n'
        '# Auto-generated by PDEnsorflow setup.py: restore LD_LIBRARY_PATH.\n'
        'if [ -n "${_PDENSORFLOW_OLD_LD_LIBRARY_PATH}" ]; then\n'
        '    export LD_LIBRARY_PATH="${_PDENSORFLOW_OLD_LD_LIBRARY_PATH}"\n'
        'else\n'
        '    unset LD_LIBRARY_PATH\n'
        'fi\n'
        'unset _PDENSORFLOW_OLD_LD_LIBRARY_PATH\n'
    )
    try:
        os.makedirs(activate_dir, exist_ok=True)
        os.makedirs(deactivate_dir, exist_ok=True)
        with open(os.path.join(activate_dir, 'zzz_pdensorflow_cuda_ld.sh'), 'w') as f:
            f.write(activate_sh)
        with open(os.path.join(deactivate_dir, 'zzz_pdensorflow_cuda_ld.sh'), 'w') as f:
            f.write(deactivate_sh)
        print('PDEnsorflow: wrote conda CUDA activation hook under {}'.format(activate_dir))
    except OSError as err:
        print('PDEnsorflow: could not write conda CUDA hook ({}); gpuSolve will '
              'still set LD_LIBRARY_PATH at import time.'.format(err))


def _read_version():
    # Single source of truth: parse gpuSolve/_version.py WITHOUT importing it
    # (an import would drag TensorFlow into the build).
    version_file = os.path.join(os.path.dirname(__file__),
                                'PDEnsorflow', 'gpuSolve', '_version.py')
    with io.open(version_file, encoding='utf-8') as fh:
        tree = ast.parse(fh.read())
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(
                isinstance(t, ast.Name) and t.id == '__version__' for t in node.targets):
            return '.'.join(str(p) for p in ast.literal_eval(node.value))
    raise RuntimeError('Could not find __version__ in {}'.format(version_file))


setup(
    name='PDEnsorflow',
    version=_read_version(),
    url='https://github.com/cesare-corrado/PDEnsorflow',
    author='Cesare Corrado',
    install_requires=['nibabel', 'imageio', 'numpy','scipy',
                      'tensorflow[and-cuda]; sys_platform == "linux"',
                      'tensorflow; sys_platform != "linux"'],
    author_email='c.corrado@imperial.ac.uk',
    description='A PDE solver using Tensorflow',
    packages=find_packages('PDEnsorflow'),
    package_dir={'': 'PDEnsorflow'},
    py_modules=[os.path.splitext(os.path.basename(path))[0] for path in glob('PDEnsorflow/*.py')],
    platforms='any',
    classifiers=[
        'Programming Language :: Python',
        'Development Status :: 4 - Beta',
        'Natural Language :: English',
        'Operating System :: OS Independent',
        ]
)

# CLAUDE-OPTIMIZE: self-configure the conda env's GPU library path at install
# time so `pip install -e .` needs no manual LD_LIBRARY_PATH or activate hook.
_install_conda_cuda_hook()
