import os
import io
import ast
from glob import glob
import os
from setuptools import setup
from setuptools import find_packages


def _install_conda_cuda_hook():
    # CLAUDE-OPTIMIZE: make `pip install -e .` self-configuring for the GPU.
    # The pip CUDA wheels (nvidia-*-cu12) live in site-packages/nvidia/*/lib and
    # TensorFlow needs them on LD_LIBRARY_PATH *before* python starts (the linker
    # reads it once at process start). When we are being installed into a conda
    # env, drop an activation hook so even a bare `import tensorflow` finds the
    # GPU with no manual step. The same hook pins XLA's ptxas to the wheel copy
    # (see the comment in the script) because a system CUDA toolkit in the wrong
    # version range makes XLA refuse to compile any GPU kernel. Outside conda
    # there is no CONDA_PREFIX, so this is a no-op and gpuSolve/__init__.py still
    # sets the path and re-execs at import.
    conda_prefix = os.environ.get('CONDA_PREFIX')
    if not conda_prefix or not os.path.isdir(conda_prefix):
        return
    activate_dir   = os.path.join(conda_prefix, 'etc', 'conda', 'activate.d')
    deactivate_dir = os.path.join(conda_prefix, 'etc', 'conda', 'deactivate.d')
    # glob nvidia/*/lib at activation time (not install time) so the hook is
    # robust to the env's python version and to wheels added later.
    activate_sh = (
        '#!/bin/bash\n'
        '# Auto-generated by PDEnsorflow setup.py: put the pip-installed CUDA\n'
        '# (nvidia-*-cu12) libs and the env lib dir on LD_LIBRARY_PATH so that\n'
        '# TensorFlow can dlopen them without importing gpuSolve first.\n'
        'export _PDENSORFLOW_OLD_LD_LIBRARY_PATH="${LD_LIBRARY_PATH}"\n'
        '_pdt_nv=""\n'
        'for _pdt_d in "${CONDA_PREFIX}"/lib/python*/site-packages/nvidia/*/lib; do\n'
        '    [ -d "${_pdt_d}" ] && _pdt_nv="${_pdt_nv}${_pdt_d}:"\n'
        'done\n'
        'export LD_LIBRARY_PATH="${_pdt_nv}${CONDA_PREFIX}/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"\n'
        '# Pin the PTX assembler to the one shipped by the nvidia-cuda-nvcc-cu12\n'
        '# wheel. XLA searches several roots for ptxas and a system CUDA toolkit\n'
        '# can win that search; releases 12.0 to 12.6.2 miscompile clamping edge\n'
        '# cases, so XLA refuses them and no GPU kernel compiles at all. The\n'
        '# wheel directory holds both bin/ptxas and nvvm/libdevice, which is what\n'
        '# --xla_gpu_cuda_data_dir must point at. An XLA_FLAGS that already names\n'
        '# a data dir is left alone: an explicit choice by the user wins.\n'
        '_pdt_nvcc=""\n'
        'for _pdt_d in "${CONDA_PREFIX}"/lib/python*/site-packages/nvidia/cuda_nvcc; do\n'
        '    [ -x "${_pdt_d}/bin/ptxas" ] && _pdt_nvcc="${_pdt_d}"\n'
        'done\n'
        'export _PDENSORFLOW_OLD_XLA_FLAGS="${XLA_FLAGS}"\n'
        'if [ -n "${_pdt_nvcc}" ] && [ "${XLA_FLAGS#*--xla_gpu_cuda_data_dir}" = "${XLA_FLAGS}" ]; then\n'
        '    export XLA_FLAGS="${XLA_FLAGS:+${XLA_FLAGS} }--xla_gpu_cuda_data_dir=${_pdt_nvcc}"\n'
        'fi\n'
        'unset _pdt_nv _pdt_nvcc _pdt_d\n'
    )
    deactivate_sh = (
        '#!/bin/bash\n'
        '# Auto-generated by PDEnsorflow setup.py: restore LD_LIBRARY_PATH and\n'
        '# XLA_FLAGS. An empty saved value is treated as "was not set", which is\n'
        '# the same convention the activation script writes it with.\n'
        'if [ -n "${_PDENSORFLOW_OLD_LD_LIBRARY_PATH}" ]; then\n'
        '    export LD_LIBRARY_PATH="${_PDENSORFLOW_OLD_LD_LIBRARY_PATH}"\n'
        'else\n'
        '    unset LD_LIBRARY_PATH\n'
        'fi\n'
        'if [ -n "${_PDENSORFLOW_OLD_XLA_FLAGS}" ]; then\n'
        '    export XLA_FLAGS="${_PDENSORFLOW_OLD_XLA_FLAGS}"\n'
        'else\n'
        '    unset XLA_FLAGS\n'
        'fi\n'
        'unset _PDENSORFLOW_OLD_LD_LIBRARY_PATH _PDENSORFLOW_OLD_XLA_FLAGS\n'
    )
    try:
        os.makedirs(activate_dir, exist_ok=True)
        os.makedirs(deactivate_dir, exist_ok=True)
        with open(os.path.join(activate_dir, 'zzz_pdensorflow_cuda_ld.sh'), 'w') as f:
            f.write(activate_sh)
        with open(os.path.join(deactivate_dir, 'zzz_pdensorflow_cuda_ld.sh'), 'w') as f:
            f.write(deactivate_sh)
        print('PDEnsorflow: wrote conda CUDA activation hook under {}'.format(activate_dir))
    except OSError as err:
        print('PDEnsorflow: could not write conda CUDA hook ({}); gpuSolve will '
              'still set LD_LIBRARY_PATH at import time.'.format(err))


def _read_version():
    # Single source of truth: parse gpuSolve/_version.py WITHOUT importing it
    # (an import would drag TensorFlow into the build).
    version_file = os.path.join(os.path.dirname(__file__),
                                'PDEnsorflow', 'gpuSolve', '_version.py')
    with io.open(version_file, encoding='utf-8') as fh:
        tree = ast.parse(fh.read())
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(
                isinstance(t, ast.Name) and t.id == '__version__' for t in node.targets):
            return '.'.join(str(p) for p in ast.literal_eval(node.value))
    raise RuntimeError('Could not find __version__ in {}'.format(version_file))


setup(
    name='PDEnsorflow',
    version=_read_version(),
    url='https://github.com/cesare-corrado/PDEnsorflow',
    author='Cesare Corrado',
    install_requires=['nibabel', 'imageio', 'numpy','scipy',
                      'tensorflow[and-cuda]; sys_platform == "linux"',
                      'tensorflow; sys_platform != "linux"'],
    author_email='c.corrado@imperial.ac.uk',
    description='A PDE solver using Tensorflow',
    packages=find_packages('PDEnsorflow'),
    package_dir={'': 'PDEnsorflow'},
    py_modules=[os.path.splitext(os.path.basename(path))[0] for path in glob('PDEnsorflow/*.py')],
    # The parameter-file front end is installed as a command. It lives inside
    # gpuSolve, so importing it triggers the usual LD_LIBRARY_PATH setup and
    # re-exec before any argument is acted on; sys.argv survives that intact.
    entry_points={
        'console_scripts': [
            'PDEnsorflow = gpuSolve.carp_compatibility.main:main',
            'singlecell = gpuSolve.carp_compatibility.singlecell:main',
        ],
    },
    platforms='any',
    classifiers=[
        'Programming Language :: Python',
        'Development Status :: 4 - Beta',
        'Natural Language :: English',
        'Operating System :: OS Independent',
        ]
)

# CLAUDE-OPTIMIZE: self-configure the conda env's GPU library path at install
# time so `pip install -e .` needs no manual LD_LIBRARY_PATH or activate hook.
_install_conda_cuda_hook()
